version: "3.8"

networks:
  humanity:
    driver: bridge
    name: humanity

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    container_name: NeptuneDDNS2
    environment:
      - API_KEY=d68c6c74968264f7693b1eb51bce42df58555
      - ZONE=neptune-network.com
      - SUBDOMAIN=oracle
      - PROXIED=true
      - RRTYPE=A
      - EMAIL=nathan@wimmerait.com.au
    deploy:
      resources:
        limits:
          memory: 100m

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    ports:
      - 7818:81
      - 80:80
      - 443:443
      - 30000:3000
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  netdata:
    image: netdata/netdata:edge
    container_name: netdata
    hostname: Oracle-1
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NETDATA_CLAIM_TOKEN=I3-yZjYQnJCGi0AHBt1gAx9J1Rmq8dyIk9m8flGvif50KrQl718vSB6xDPdsQ-3bjFr4-xlVD2RvRo8yTHsXjs1mUvDQfXWDwEqBEsa-oSHQemzmrDI8BcS8o6_bj38jk5cg-Bw
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=9cecebce-f955-4d4d-89fe-d29d0f114912
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
