---
version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex
    network_mode: host
    environment:
      - PUID=99
      - PGID=100
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-FpPkAMygUTbyPbzgu7xG
    volumes:
      - /mnt/user/transcode/plex:/transcode
      - /mnt/user/Media/Movies/:/Movies
      - "/mnt/user/Media/TV Shows/:/TV-Shows"
      - /mnt/user/Media/Music/:/Music
      - /mnt/user/Media/Anime/:/Anime
      - "/mnt/user/Media/Anime Movies/:/Animemovies"
      - /mnt/user/appdata/Plex-Media-Server:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 5g
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  plex-private:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex-Private
    networks:
      br0:
        ipv4_address: 192.168.1.251
    environment:
      - PUID=99
      - PGID=100
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-VK3s_XyeGxSFgbhP-PoH
    volumes:
      - /mnt/user/transcode/plex-priv:/transcode
      - /mnt/user/XXX/:/data
      - /mnt/user/appdata/Plex-Private:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 5g
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  br0:
    driver: ipvlan
    external: true
