version: "3.8"
services:
  cronicle:
    image: soulteary/cronicle:latest
    container_name: cronicle
    hostname: cronicle
    ports:
      - 3012:3012
    restart: always
    volumes:
      - cronicle:/opt/cronicle

volumes:
  cronicle:
    name: cronicle
