version: "3.8"
services:
  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    ports:
      - 7818:81
      - 80:80
      - 443:443
      - 30000:3000
    restart: always
    volumes:
      - nginx-data:/data
      - nginx-letsencrypt:/etc/letsencrypt

volumes:
  nginx-data:
  nginx-letsencrypt:

networks:
  default:
    external: true
    name: humanity
